[package]
name = "sundries"
version = "0.1.0"
authors = ["tsai phan <phanalpha@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
regex = "1"
serde = "1"
